-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 00:53:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rubydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rubydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rubydb` DEFAULT CHARACTER SET utf8 ;
USE `rubydb` ;

-- -----------------------------------------------------
-- Table `rubydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubydb`.`books` (
  `name` VARCHAR(50) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
